"""Fractional differentiation (López de Prado, AFML ch. 5).

There is a tension at the heart of feature engineering for prices: integer
differencing (returns) makes a series stationary — a requirement for most
models — but erases the *memory* (level information) that carries the
signal. Fractional differentiation resolves it: differencing by a real
order ``d`` in ``[0, 1]`` removes just enough of the trend to pass a
stationarity test while retaining as much memory as possible.

The series is convolved with the binomial weights of the fractional
difference operator ``(1 − L)^d``::

    w_0 = 1,   w_k = −w_{k−1} · (d − k + 1) / k

which decay toward zero. The **fixed-width window** (FFD) variant drops
weights once ``|w_k|`` falls below ``threshold`` and applies the same
finite kernel at every bar, so the transform is causal, shift-invariant
and has a constant warm-up. ``d = 0`` returns the input unchanged;
``d = 1`` reproduces the first difference.

Direct-import module::

    from src.data.fracdiff import frac_diff_ffd, ffd_weights
"""

from __future__ import annotations

import numpy as np
import pandas as pd


def ffd_weights(d: float, threshold: float = 1e-4, max_width: int = 10_000) -> np.ndarray:
    """Fixed-width fractional-difference weights ``[w_0, w_1, ...]``.

    Weights are generated by the recursion ``w_k = −w_{k−1}(d−k+1)/k`` and
    truncated once ``|w_k| < threshold`` (or ``max_width`` is reached).

    Args:
        d: Differencing order (>= 0); non-integer allowed.
        threshold: Drop weights smaller in magnitude than this.
        max_width: Hard cap on the number of weights (guards ``d`` near 0
            with a tiny threshold, where the tail decays very slowly).

    Returns:
        1-D array of weights, newest-lag first (``w_0 = 1``).

    Raises:
        ValueError: If ``d`` < 0, ``threshold`` <= 0 or ``max_width`` < 1.
    """
    if d < 0:
        raise ValueError(f"d must be >= 0, got {d}.")
    if threshold <= 0:
        raise ValueError(f"threshold must be > 0, got {threshold}.")
    if max_width < 1:
        raise ValueError(f"max_width must be >= 1, got {max_width}.")

    weights = [1.0]
    k = 1
    while k < max_width:
        w = -weights[-1] * (d - k + 1) / k
        if abs(w) < threshold:
            break
        weights.append(w)
        k += 1
    return np.array(weights, dtype=float)


def frac_diff_ffd(
    series: pd.Series,
    d: float,
    threshold: float = 1e-4,
    max_width: int = 10_000,
) -> pd.Series:
    """Fixed-width fractionally differentiated series.

    Convolves ``series`` with :func:`ffd_weights`, applying the same finite
    kernel at every bar. The first ``len(weights) − 1`` bars are NaN (the
    kernel does not fit). ``d = 0`` returns a copy of the input; ``d = 1``
    returns its first difference.

    Args:
        series: Input series (typically log prices), NaN-free.
        d: Differencing order (>= 0).
        threshold: Weight-truncation threshold (see :func:`ffd_weights`).
        max_width: Hard cap on the kernel width.

    Returns:
        Series named ``"frac_diff"`` aligned to ``series``.

    Raises:
        ValueError: If ``series`` contains NaNs (or the parameters are
            invalid, raised by :func:`ffd_weights`).
    """
    values = series.to_numpy(dtype=float)
    if np.isnan(values).any():
        raise ValueError("series must not contain NaNs.")

    weights = ffd_weights(d, threshold=threshold, max_width=max_width)
    width = len(weights)
    out = np.full(len(values), np.nan)
    # weights are newest-lag first; dot with the trailing window reversed
    kernel = weights[::-1]
    for t in range(width - 1, len(values)):
        out[t] = float(kernel @ values[t - width + 1 : t + 1])
    return pd.Series(out, index=series.index, name="frac_diff")
